import React from 'react';

export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      key="lato300"
      rel="preload"
      href="./fonts/lato-v23-latin-300.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="lato400"
      rel="preload"
      href="./fonts/lato-v23-latin-regular.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="lato700"
      rel="preload"
      href="./fonts/lato-v23-latin-700.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="vollkornBlack"
      rel="preload"
      href="./fonts/vollkorn-v21-latin-900.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />,
    <link
      key="vollkornExtraBold"
      rel="preload"
      href="./fonts/vollkorn-v21-latin-800.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
    />
  ]);
};