backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Hauptseiten"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Hero, name: hero, widget: object, collapsed: true, summary: '{{fields.title}}: {{fields.lead}}', fields: [{ label: Bilder, name: images, widget: list, minimize_collapsed: true, fields: [{label: Titel, name: title, widget: "string"}, {label: Bild, name: image, widget: image}, {label: Link, name: link, widget: "string"}]}, { label: Titel, name: title, widget: string }, { label: Lead, name: lead, widget: string }, { label: CTA, name: cta, widget: object, fields: [{  label: Text, name: text, widget: string }, {  label: Link, name: link, widget: string }] }] }
          - { label: Rechtsgebiete, name: recht, widget: object, collapsed: true, summary: '{{fields.lead}}: {{fields.category.*}}', fields: [{ label: Lead, name: lead, widget: string }, { label: Rechtsgebiete, name: category, widget: relation, collection: recht, value_field: title, search_fields: [title, picture], multiple: true, max: 3 }] }
          - { label: Seiteneinstellungen, name: settings, widget: object, collapsed: true, summary: '{{fields.site}}: {{fields.description}}', fields: [{ label: "Seitenname", name: "site", widget: "string" }, { label: "Beschreibung", name: "description", widget: "string" }, { label: "SEO Beschreibung", name: "seo", widget: "text" }, { label: "Bild", name: "image", widget: image }, { label: "Hauptmenü", name: menu, widget: list, minimize_collapsed: true, fields: [{label: Name, name: name, widget: "string"}, {label: URL, name: to, widget: "string", required: false}] }, { label: "Footermenü", name: footermenu, widget: list, minimize_collapsed: true, fields: [{label: Name, name: name, widget: "string"}, {label: URL, name: to, widget: "string", required: false}] }, { label: "Kontakt", name: contact, widget: object, fields: [{label: "Information", name: "info", widget: "markdown"}, {label: "Kontakt", name: "contact", widget: "markdown"}, { label: "Karte", name: "map", widget: image }, {label: "Öffnungszeiten", name: "open", widget: "markdown"}, {label: "Einleitung", name: "intro", widget: "markdown"}, {label: "Bild", name: "image", widget: image},{label: "Bildunterschrift", name: "bu", widget: "markdown"}] }] }
          - { label: Title, name: title, widget: string }
          - { label: Lead, name: lead, widget: string }
          - { label: CTA Text, name: ctatext, widget: string }
          - { label: CTA Link, name: ctalink, widget: string }
          - { label: Rechtsbereiche, name: rechtsbereiche, widget: string }
          - { label: Images, name: images, widget: list, fields: [{label: Titel, name: title, widget: "string"}, {label: Image, name: image, widget: image}, {label: Link, name: link, widget: "string"}]}
          - { label: "Seitenname", name: "site", widget: "string" }
          - { label: "Beschreibung", name: "description", widget: "string" }
          - { label: "SEO Beschreibung", name: "seo", widget: "text" }
          - { label: "Bild", name: "image", widget: image }
          - { label: "Google Analytics ID", name: "gaid", widget: "string" }
          - { label: "Hauptmenü", name: menu, widget: list, fields: [{label: Name, name: name, widget: "string"}, {label: URL, name: to, widget: "string"}] }
          - { label: "Footermenü", name: footermenu, widget: list, fields: [{label: Name, name: name, widget: "string"}, {label: URL, name: to, widget: "string"}] }
          - { label: "Kontakt", name: contact, widget: object, fields: [{label: "Information", name: "info", widget: "markdown"}, {label: "Kontakt", name: "contact", widget: "markdown"}, {label: "Öffnungszeiten", name: "open", widget: "markdown"}, {label: "Einleitung", name: "intro", widget: "markdown"}, {label: "Bild", name: "image", widget: image},{label: "Bildunterschrift", name: "bu", widget: "markdown"}] }
      - file: "src/pages/anwalt/index.md"
        label: "Anwalt"
        name: "anwalt"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "anwalt-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Featured Image", name: "featuredimage", widget: image }
          - { label: "Subtitle", name: "subtitle", widget: "string"}
          - { label: Lead, name: lead, widget: string}
          - { label: "Link", name: "link", widget: "relation", collection: "blog", value_field: "slug", search_fields: ["title", "recht"] }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/impressum/index.md"
        label: "Impressum"
        name: "impressum"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "impressum-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/datenschutz/index.md"
        label: "Datenschutz"
        name: "datenschutz"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "datenschutz-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
  - name: "userpages"
    label: "Seiten"
    folder: "src/pages/page"
    create: true
    slug: "/{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "userpages-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Aktuelles"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {label: "Rechtsbereich", name: "recht", widget: "relation", collection: "recht", search_fields: ["title"], value_field: "title", display_fields: ["title"], required: false}
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean", required: false}
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "recht"
    label: "Rechtsgebiete"
    folder: "src/pages/recht"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "recht-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: Lead, name: lead, widget: string}
      - {label: Icon, name: image, widget: image}
      - {label: Bild, name: picture, widget: image}
      - {label: "Banner", name: banner, widget: list, fields: [{label: Titel, name: title, widget: "string"}, {label: Absatz, name: text, widget: "text"}]}
      - {label: "Beitrag", name: article, widget: list, fields: [{label: Titel, name: title, widget: "string"}, {label: Body, name: body, widget: "markdown"}]}
