backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Aktuelles"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {label: "Rechtsbereich", name: "recht", widget: "relation", collection: "recht", search_fields: ["title"], value_field: "title", display_fields: ["title"]}
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Lead, name: lead, widget: string }
          - { label: CTA Text, name: ctatext, widget: string }
          - { label: CTA Link, name: ctalink, widget: string }
          - { label: Rechtsbereiche, name: rechtsbereiche, widget: string }
          - { label: Images, name: images, widget: list, fields: [{label: Titel, name: title, widget: "string"}, {label: Image, name: image, widget: image}, {label: Link, name: link, widget: "string"}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/impressum/index.md"
        label: "Impressum"
        name: "impressum"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "impressum-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: Lead, name: lead, widget: string}
        - {label: Icon, name: icon, widget: image}
        - {label: Bild, name: image, widget: image}
        - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/datenschutz/index.md"
        label: "Datenschutz"
        name: "datenschutz"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "datenschutz-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: Lead, name: lead, widget: string}
        - {label: Icon, name: icon, widget: image}
        - {label: Bild, name: image, widget: image}
        - {label: "Body", name: "body", widget: "markdown"}
  - name: "settings"
    label: "Einstellungen"
    delete: false
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        name: "global"
        label: "Seite"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "settings"}
          - {label: "Seitenname", name: "site", widget: "string"}
          - {label: "Beschreibung", name: "description", widget: "string"}
          - {label: "SEO Beschreibung", name: "seo", widget: "text"}
          - {label: "Bild", name: "image", widget: image}
          - {label: "Hauptmenü", name: menu, widget: list, fields: [{label: Name, name: name, widget: "string"}, {label: URL, name: to, widget: "string"}]}
          - {label: "Footermenü", name: footermenu, widget: list, fields: [{label: Name, name: name, widget: "string"}, {label: URL, name: to, widget: "string"}]}
          - {label: "Kontakt", name: contact, widget: object, fields: [{label: "Information", name: "info", widget: "markdown"}, {label: "Kontakt", name: "contact", widget: "markdown"}, {label: "Öffnungszeiten", name: "open", widget: "markdown"}]}
  - name: "recht"
    label: "Rechtsfragen"
    folder: "src/pages/recht"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "recht-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: Lead, name: lead, widget: string}
      - {label: Icon, name: image, widget: image}
      - {label: Bild, name: picture, widget: image}
      - {label: "Banner", name: banner, widget: list, fields: [{label: Titel, name: title, widget: "string"}, {label: Absatz, name: text, widget: "text"}]}
      - {label: "Beitrag", name: article, widget: list, fields: [{label: Titel, name: title, widget: "string"}, {label: Body, name: body, widget: "markdown"}]}
  